import gql from 'graphql-tag'

export const CREATE_SCORE = gql`mutation createScore($implementationId: ID!, $studentId: ID!, $userId: ID!, $comment: String!, $score: Float!) {
                        updateImplementation(id: $implementationId, score: {userId: $userId, studentId: $studentId, comment: $comment, score: $score}) {
                            score {
                                id
                                score
                                comment
                            }
                        }
                    }
                  `;