import gql from 'graphql-tag'

export const DELETE_STUDENT = gql`mutation deleteStudent($id: ID!){
                                deleteStudent(id: $id) {
                                  id
                                }}
                `;