import gql from 'graphql-tag'

export const SIGNUP_USER = gql`mutation {
                        signupUser(email: $email, password: $password, name: $name, company: $company, isAdmin: $isAdmin) {
                            id
                            token
                        }
                    }
                  `;