import gql from 'graphql-tag'

export const STUDENT = gql`query Student($id: ID!) {
    Student(id: $id) {
        id,
        email,
        name,
        event {
            id
            weights{
                id
                project {
                    id
                    name
                }
            }
        }
        meetings {
            id
        }
        implementations {
            id
        }
        performance {
            id
        }

    }
}
                `;