import gql from 'graphql-tag'

export const STUDENT = gql`query Student($id: ID!) {
    Student(id: $id, softDelete: false) {
        id,
        email,
        name,
        event {
            id
            weights{
                id
                project {
                    id
                    name
                }
            }
        }
        implementations {
            id
            project {
                id
                name
            }
            score {
                id
                score
                comment
                user {
                    id
                }
            }
            urlProject
            urlRepo
        }
        performance {
            id
        }
    }
}
                `;