import gql from 'graphql-tag'

export const STUDENT = gql`query Student($id: ID!) {
    Student(id: $id) {
        id,
        email,
        name,
        event {
            id
            weights{
                id
                project {
                    id
                    name
                }
            }
        }
        meetings {
            id
            user {
                id
            }
            student{
                id
                name
            }
            event {
                id
                weights {
                    id
                    project {
                        id
                        name
                    }
                }
            }
            scores {
                id
                implementation {
                    id
                    project {
                        id
                        name
                    }
                }
                score
                comment
            }
        }
        implementations {
            id
        }
        performance {
            id
        }
    }
}
                `;