import gql from 'graphql-tag'

export const SUB_SCORE_CREATED = gql`subscription scoreCreated($studentId: ID!, $userId: ID!, $eventId: ID!) {
                                    Score(
                                        filter: {
                                            mutation_in: [CREATED]
                                            node: {
                                                student {
                                                    id: $studentId
                                                }
                                                event {
                                                    id: $eventId
                                                }
                                                user {
                                                    id: $userId
                                                }
                                            }
                                        }
                                    ) {
                                        mutation
                                        node {
                                            id
                                            student {
                                                id
                                            }
                                            user {
                                                id
                                            }
                                            implementation {
                                                id
                                            }
                                            event {
                                                id
                                            }
                                            comment
                                            score
                                        }
                                    }
                                    }
                  `;