import gql from 'graphql-tag'

export const USER = gql`query User($id: ID!) {
    User(id: $id) {
        id,
        email,
        name,
        company,
        isAdmin,
        events {
            id,
            courseName,
            academicYear,
            students {
                id
                name
                email
            },
            jurys{
                id
                name
                email
                company
            },
            examSession,
            weights {
                id
                weight
                project {
                    id
                    name
                }
            }
            softDelete
        }
        scores {
            id
            score
            comment
            student {
                id
            }
            implementation {
                id 
                project {
                    id 
                    name
                }
            }
        }
    }
}
                `;